"use client";

import { useEffect, useState } from "react";
import { apiRequest } from "@/lib/api";

export const fallbackResume = {
  basic: { fullName: "Aditya Kumawat", role: "Full Stack Web Developer | Internship & Junior Developer Roles", location: "Jaipur, Rajasthan", phone: "6378891872", email: "aadityakumawat6165@gmail.com", linkedin: { label: "linkedin.com/in/aditya-kumawat-b936ab31a", url: "https://www.linkedin.com/in/aditya-kumawat-b936ab31a" }, github: { label: "github.com/aadi-kumawat01", url: "https://github.com/aadi-kumawat01" } },
  summary: "Full Stack Web Developer focused on building responsive web applications with Next.js, Node.js, Express.js and MongoDB. Built individual full-stack projects including a complete e-commerce platform and a role-based cafe management system. Looking for internship or junior developer opportunities where I can contribute to frontend and backend development while working on real products.",
  skillGroups: [{ name: "Frontend", skills: ["HTML", "CSS", "JavaScript", "React.js", "Next.js", "Tailwind CSS", "Bootstrap"], order: 1 }, { name: "Backend", skills: ["Node.js", "Express.js"], order: 2 }, { name: "Database", skills: ["MongoDB"], order: 3 }, { name: "Version Control", skills: ["Git"], order: 4 }],
  projects: [{ title: "Nestro E-commerce", dateLabel: "August 2026 | Individual Project", techStack: ["Next.js", "Node.js", "Express.js", "MongoDB", "Tailwind CSS"], liveUrl: "https://nestro-one.vercel.app/", githubUrl: "https://github.com/aadi-kumawat01/nestro", bullets: ["Built an end-to-end e-commerce application with authentication, product browsing, search and filtering, cart, wishlist, checkout, orders and admin management.", "Implemented COD and Razorpay payment flows, user profile/address management and responsive interfaces for mobile, tablet and desktop.", "Used Express.js APIs and MongoDB to manage users, products, carts, orders and store data across the application."], order: 1 }, { title: "Cafe Management System", dateLabel: "September 2026 | Individual Project", techStack: ["Next.js", "Node.js", "Express.js", "MongoDB", "Tailwind CSS"], bullets: ["Built a full-stack cafe management application with role-based access for Admin, Waiter and Kitchen/Cook users.", "Implemented permission-based access so each user role can work with the parts of the system required for its responsibilities.", "Developed responsive frontend screens and backend APIs with MongoDB for application data and access-controlled workflows."], order: 2 }],
  education: [{ title: "Bachelor of Arts (B.A.)", yearLabel: "2025 - 2028", institution: "Govt Arts College, Sikar", details: "Pandit Deendayal Upadhyaya Shekhawati University, Sikar • Currently 2nd Year", order: 1 }, { title: "Class XII - Science (Mathematics)", yearLabel: "2024", institution: "Bright Sr. Sec. School • RBSE", score: "90.60%", order: 2 }, { title: "Class X", yearLabel: "2022", institution: "Bright Sr. Sec. School • RBSE", score: "79%", order: 3 }],
  training: [{ title: "MERN Full Stack Development", details: "WsCube Career School, Jaipur • 6-month program • March 2026 - September 2026", certificateStatus: "Certification expected September 2026", order: 1 }],
  achievements: [{ title: "1st Position", description: "DOMinate with JavaScript - Coding Event, WsCube Career School, Jaipur • 27 June 2026", order: 1 }, { title: "2nd Position", description: "Cascading Creativity - Coding Event, WsCube Career School, Jaipur • 23 May 2026", order: 2 }],
  languages: [{ name: "Hindi", order: 1 }, { name: "English", order: 2 }], visible: true,
};

function SectionTitle({ children }) { return <h2 className="mb-3 mt-7 border-b border-zinc-200 pb-2 text-sm font-bold uppercase tracking-[0.12em] text-zinc-950">{children}</h2>; }
function byOrder(items = []) { return [...items].sort((a, b) => (a.order || 0) - (b.order || 0)); }

function ResumeSkeleton() {
  return <article aria-label="Loading resume" className="mx-auto max-w-[900px] animate-pulse bg-white px-6 py-8 shadow-[0_30px_100px_rgba(0,0,0,0.35)] sm:px-10 sm:py-10 lg:px-14 lg:py-12"><div className="mx-auto h-10 w-64 rounded bg-zinc-200" /><div className="mx-auto mt-3 h-5 w-96 max-w-full rounded bg-zinc-100" /><div className="mt-8 space-y-4">{Array.from({ length: 6 }).map((_, index) => <div key={index} className="space-y-2"><div className="h-4 w-40 rounded bg-zinc-200" /><div className="h-3 w-full rounded bg-zinc-100" /><div className="h-3 w-4/5 rounded bg-zinc-100" /></div>)}</div></article>;
}

export default function ResumeDocument() {
  const [resume, setResume] = useState(null);
  useEffect(() => {
    const controller = new AbortController();
    apiRequest("/api/resume", { signal: controller.signal }).then((response) => {
      const content = response?.data;
      setResume(content?.basic?.fullName ? content : fallbackResume);
    }).catch((error) => { if (error.name !== "AbortError") setResume(fallbackResume); });
    return () => controller.abort();
  }, []);
  if (!resume) return <ResumeSkeleton />;
  if (resume.visible === false) return null;
  const { basic } = resume;
  return <article className="mx-auto max-w-[900px] bg-white px-6 py-8 text-zinc-800 shadow-[0_30px_100px_rgba(0,0,0,0.35)] sm:px-10 sm:py-10 lg:px-14 lg:py-12">
    <header className="border-b border-zinc-200 pb-5 text-center"><h1 className="text-3xl font-extrabold tracking-tight text-zinc-950 sm:text-4xl">{basic.fullName?.toUpperCase()}</h1>{basic.role && <p className="mt-2 text-sm font-semibold text-zinc-700 sm:text-base">{basic.role}</p>}<div className="mx-auto mt-4 flex max-w-3xl flex-wrap justify-center gap-x-3 gap-y-1 text-xs leading-5 text-zinc-600 sm:text-sm">{basic.location && <span>{basic.location}</span>}{basic.phone && <><span className="text-zinc-300">|</span><a href={`tel:${basic.phone}`} className="transition hover:text-zinc-950">{basic.phone}</a></>}{basic.email && <><span className="text-zinc-300">|</span><a href={`mailto:${basic.email}`} className="transition hover:text-zinc-950">{basic.email}</a></>}</div><div className="mt-1 flex flex-wrap justify-center gap-x-3 gap-y-1 text-xs text-zinc-600 sm:text-sm">{basic.linkedin?.url && <a href={basic.linkedin.url} target="_blank" rel="noreferrer" className="transition hover:text-zinc-950 hover:underline">{basic.linkedin.label || basic.linkedin.url}</a>}{basic.linkedin?.url && basic.github?.url && <span className="text-zinc-300">|</span>}{basic.github?.url && <a href={basic.github.url} target="_blank" rel="noreferrer" className="transition hover:text-zinc-950 hover:underline">{basic.github.label || basic.github.url}</a>}</div></header>
    {resume.summary && <><SectionTitle>Professional Summary</SectionTitle><p className="text-sm leading-6 text-zinc-700">{resume.summary}</p></>}
    {resume.skillGroups?.length > 0 && <><SectionTitle>Technical Skills</SectionTitle><div className="space-y-1.5 text-sm leading-6 text-zinc-700">{byOrder(resume.skillGroups).map((group) => <p key={group._id || group.name}><strong className="text-zinc-950">{group.name}:</strong> {group.skills?.join(", ")}</p>)}</div></>}
    {resume.projects?.length > 0 && <><SectionTitle>Projects</SectionTitle><div className="space-y-7">{byOrder(resume.projects).map((project) => <div key={project._id || project.title}><div className="flex flex-col gap-1 sm:flex-row sm:items-baseline sm:justify-between"><h3 className="text-base font-bold text-zinc-950">{project.title}</h3>{project.dateLabel && <p className="text-xs font-medium text-zinc-500">{project.dateLabel}</p>}</div>{project.techStack?.length > 0 && <p className="mt-1 text-sm text-zinc-600">{project.techStack.join(" • ")}</p>}{(project.liveUrl || project.githubUrl) && <div className="mt-2 flex gap-4 text-sm font-medium">{project.liveUrl && <a href={project.liveUrl} target="_blank" rel="noreferrer" className="text-zinc-950 underline underline-offset-4">Live Demo</a>}{project.githubUrl && <a href={project.githubUrl} target="_blank" rel="noreferrer" className="text-zinc-950 underline underline-offset-4">GitHub</a>}</div>}{project.bullets?.length > 0 && <ul className="mt-3 list-disc space-y-1.5 pl-5 text-sm leading-6 text-zinc-700">{project.bullets.map((bullet, index) => <li key={index}>{bullet}</li>)}</ul>}</div>)}</div></>}
    {resume.education?.length > 0 && <><SectionTitle>Education</SectionTitle><div className="space-y-4">{byOrder(resume.education).map((item) => <div key={item._id || item.title}><div className="flex flex-col sm:flex-row sm:justify-between"><h3 className="text-sm font-bold text-zinc-950">{item.title}</h3>{item.yearLabel && <span className="text-xs font-medium text-zinc-500">{item.yearLabel}</span>}</div>{item.institution && <p className="mt-1 text-sm text-zinc-700">{item.institution}{item.score && <> • <strong className="text-zinc-950">{item.score}</strong></>}</p>}{item.details && <p className="text-sm text-zinc-500">{item.details}</p>}</div>)}</div></>}
    {resume.training?.length > 0 && <><SectionTitle>Training & Certification</SectionTitle><div className="space-y-4">{byOrder(resume.training).map((item) => <div key={item._id || item.title}><h3 className="text-sm font-bold text-zinc-950">{item.title}</h3>{item.details && <p className="mt-1 text-sm leading-6 text-zinc-700">{item.details}</p>}{item.certificateStatus && <p className="text-sm text-zinc-500">{item.certificateStatus}</p>}</div>)}</div></>}
    {resume.achievements?.length > 0 && <><SectionTitle>Achievements</SectionTitle><ul className="list-disc space-y-2 pl-5 text-sm leading-6 text-zinc-700">{byOrder(resume.achievements).map((item) => <li key={item._id || item.title}><strong className="text-zinc-950">{item.title}</strong>{item.description && <> - {item.description}</>}</li>)}</ul></>}
    {resume.languages?.length > 0 && <><SectionTitle>Languages</SectionTitle><p className="text-sm text-zinc-700">{byOrder(resume.languages).map((item) => item.name).join(", ")}</p></>}
  </article>;
}
