"use client";

import { useEffect, useState } from "react";
import { apiRequest } from "@/lib/api";
import { AdminIntro, AdminStatus, Feedback } from "@/components/admin/HeroManager";

const emptyContact = { eyebrow: "", heading: "", description: "", availabilityText: "", email: "", location: "", formHeading: "", formDescription: "", visible: true };
const inputClass = "mt-2 w-full rounded-lg border border-white/15 bg-black/15 px-3 py-2.5 text-sm text-white outline-none focus:border-[#e82b45]";

export default function ContactManager() {
  const [contact, setContact] = useState(emptyContact); const [isLoading, setIsLoading] = useState(true); const [isSaving, setIsSaving] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { const timer = window.setTimeout(async () => { try { const response = await apiRequest("/api/admin/contact"); setContact({ ...emptyContact, ...response.data }); } catch (requestError) { setError(requestError.message); } finally { setIsLoading(false); } }, 0); return () => window.clearTimeout(timer); }, []);
  async function save(event) { event.preventDefault(); setError(""); setMessage(""); if (contact.email && !/^\S+@\S+\.\S+$/.test(contact.email)) { setError("Enter a valid email address."); return; } setIsSaving(true); try { await apiRequest("/api/admin/contact", { method: "PATCH", body: JSON.stringify(contact) }); setMessage("Contact content saved successfully."); } catch (requestError) { setError(requestError.message); } finally { setIsSaving(false); } }
  if (isLoading) return <AdminStatus text="Loading contact content..." />;
  return <form onSubmit={save} className="space-y-6"><AdminIntro title="Contact Management" text="Edit public contact content without changing the contact form behavior." /><section className="grid gap-4 rounded-2xl border border-white/10 bg-white/[0.03] p-5 sm:grid-cols-2 sm:p-6"><Field label="Eyebrow" value={contact.eyebrow} onChange={(value) => setContact((current) => ({ ...current, eyebrow: value }))} /><Field label="Email" value={contact.email} type="email" onChange={(value) => setContact((current) => ({ ...current, email: value }))} /><Field label="Heading" value={contact.heading} className="sm:col-span-2" onChange={(value) => setContact((current) => ({ ...current, heading: value }))} /><Field label="Description" value={contact.description} multiline className="sm:col-span-2" onChange={(value) => setContact((current) => ({ ...current, description: value }))} /><Field label="Availability Text" value={contact.availabilityText} onChange={(value) => setContact((current) => ({ ...current, availabilityText: value }))} /><Field label="Location" value={contact.location} onChange={(value) => setContact((current) => ({ ...current, location: value }))} /><Field label="Form Heading" value={contact.formHeading} className="sm:col-span-2" onChange={(value) => setContact((current) => ({ ...current, formHeading: value }))} /><Field label="Form Description" value={contact.formDescription} multiline className="sm:col-span-2" onChange={(value) => setContact((current) => ({ ...current, formDescription: value }))} /><label className="flex items-center gap-3 text-sm font-medium text-white/80 sm:col-span-2"><input type="checkbox" checked={contact.visible} onChange={(event) => setContact((current) => ({ ...current, visible: event.target.checked }))} /> Show Contact section</label></section><Feedback error={error} message={message} /><button disabled={isSaving} className="rounded-lg bg-[#e82b45] px-5 py-3 text-sm font-semibold text-white disabled:opacity-60">{isSaving ? "Saving..." : "Save Contact"}</button></form>;
}
function Field({ label, value, onChange, multiline = false, className = "", type = "text" }) { return <label className={`block text-sm font-medium text-white/80 ${className}`}>{label}{multiline ? <textarea value={value} onChange={(event) => onChange(event.target.value)} rows="4" className={inputClass} /> : <input type={type} value={value} onChange={(event) => onChange(event.target.value)} className={inputClass} />}</label>; }
