"use client";

import { useEffect, useState } from "react";
import { apiRequest } from "@/lib/api";
import { AdminIntro, AdminStatus, Feedback, Field } from "@/components/admin/HeroManager";
import FileUploadField from "@/components/admin/FileUploadField";
import { fallbackResume } from "@/components/resume/ResumeDocument";

const emptyContent = { basic: { fullName: "", role: "", location: "", phone: "", email: "", linkedin: { label: "", url: "" }, github: { label: "", url: "" } }, summary: "", skillGroups: [], projects: [], education: [], training: [], achievements: [], languages: [], visible: true };
const emptyPdf = { pdfUrl: "", downloadUrl: "", downloadFileName: "", publicId: "" };
const textList = (value) => (value || []).join("\n");
const parseList = (value) => value.split("\n").map((item) => item.trim()).filter(Boolean);
const nextOrder = (items) => Math.max(0, ...items.map((item) => Number(item.order) || 0)) + 1;

export default function ResumeManager() {
  const [content, setContent] = useState(emptyContent);
  const [pdf, setPdf] = useState(emptyPdf);
  const [savedPdf, setSavedPdf] = useState(emptyPdf);
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [isUploading, setIsUploading] = useState(false);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");

  useEffect(() => {
    apiRequest("/api/admin/resume").then((response) => {
      const saved = response.data.content?.basic?.fullName ? response.data.content : fallbackResume;
      setContent({ ...emptyContent, ...saved, basic: { ...emptyContent.basic, ...saved.basic, linkedin: { ...emptyContent.basic.linkedin, ...saved.basic?.linkedin }, github: { ...emptyContent.basic.github, ...saved.basic?.github } } });
      const nextPdf = { ...emptyPdf, ...response.data.pdf };
      setPdf(nextPdf);
      setSavedPdf(nextPdf);
    }).catch((requestError) => setError(requestError.message)).finally(() => setIsLoading(false));
  }, []);
  function updateBasic(field, value) { setContent((current) => ({ ...current, basic: { ...current.basic, [field]: value } })); }
  function updateLink(link, field, value) { setContent((current) => ({ ...current, basic: { ...current.basic, [link]: { ...current.basic[link], [field]: value } } })); }
  function updateList(key, index, field, value) { setContent((current) => ({ ...current, [key]: current[key].map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item) })); }
  function addItem(key, item) { setContent((current) => ({ ...current, [key]: [...current[key], { ...item, order: nextOrder(current[key]), visible: true }] })); }
  function removeItem(key, index) { if (window.confirm("Remove this resume item?")) setContent((current) => ({ ...current, [key]: current[key].filter((_, itemIndex) => itemIndex !== index) })); }
  async function uploadPdf(event) { const file = event.target.files?.[0]; if (!file) return; setError(""); setMessage(""); setIsUploading(true); const body = new FormData(); body.append("resume", file); try { const response = await apiRequest("/api/admin/uploads/resume", { method: "POST", body }); setPdf({ pdfUrl: response.data.url, downloadUrl: response.data.downloadUrl, downloadFileName: file.name, publicId: response.data.publicId }); setMessage("PDF uploaded. Save Resume to publish it."); } catch (requestError) { setError(requestError.message); } finally { setIsUploading(false); event.target.value = ""; } }
  async function save(event) { event.preventDefault(); setError(""); setMessage(""); setIsSaving(true); try { await apiRequest("/api/admin/resume", { method: "PATCH", body: JSON.stringify({ content, pdf }) }); if (savedPdf.publicId && savedPdf.publicId !== pdf.publicId) { try { await apiRequest("/api/admin/uploads/resume", { method: "DELETE", body: JSON.stringify({ publicId: savedPdf.publicId }) }); } catch { setMessage("Resume saved. The previous PDF could not be deleted automatically."); } } setSavedPdf(pdf); if (!savedPdf.publicId || savedPdf.publicId === pdf.publicId) setMessage("Resume saved successfully."); } catch (requestError) { setError(requestError.message); } finally { setIsSaving(false); } }
  if (isLoading) return <AdminStatus text="Loading resume content..." />;
  return <form onSubmit={save} className="space-y-6">
    <AdminIntro title="Resume Management" text="Edit the online resume and separately upload the PDF used only for downloading." />
    <Section title="Resume PDF" description="This PDF is used only by Download Resume. See My Resume always opens the editable online resume page."><FileUploadField label="Resume PDF" buttonLabel={pdf.publicId ? "Replace PDF" : "Choose PDF"} accept="application/pdf,.pdf" helpText="PDF only · Max 10 MB" currentFileName={pdf.downloadFileName} disabled={isUploading} isUploading={isUploading} onChange={uploadPdf} />{pdf.downloadUrl && <a href={pdf.downloadUrl} target="_blank" rel="noreferrer" className="inline-flex cursor-pointer text-sm text-[#ff9baa] underline underline-offset-4">Download current PDF</a>}</Section>
    <Section title="Basic information"><div className="grid gap-4 md:grid-cols-2"><Field label="Full name" value={content.basic.fullName} onChange={(value) => updateBasic("fullName", value)} /><Field label="Role / headline" value={content.basic.role} onChange={(value) => updateBasic("role", value)} /><Field label="Location" value={content.basic.location} onChange={(value) => updateBasic("location", value)} /><Field label="Phone" value={content.basic.phone} onChange={(value) => updateBasic("phone", value)} /><Field label="Email" value={content.basic.email} onChange={(value) => updateBasic("email", value)} /><div className="hidden md:block" /><Field label="LinkedIn display text" value={content.basic.linkedin.label} onChange={(value) => updateLink("linkedin", "label", value)} /><Field label="LinkedIn URL" value={content.basic.linkedin.url} onChange={(value) => updateLink("linkedin", "url", value)} /><Field label="GitHub display text" value={content.basic.github.label} onChange={(value) => updateLink("github", "label", value)} /><Field label="GitHub URL" value={content.basic.github.url} onChange={(value) => updateLink("github", "url", value)} /></div></Section>
    <Section title="Professional summary"><Field label="Summary" multiline value={content.summary} onChange={(value) => setContent((current) => ({ ...current, summary: value }))} /></Section>
    <Collection title="Technical skills" addLabel="Add skill group" onAdd={() => addItem("skillGroups", { name: "", skills: [] })}>{content.skillGroups.map((item, index) => <ItemCard key={item._id || index} onRemove={() => removeItem("skillGroups", index)}><div className="grid gap-4 md:grid-cols-2"><Field label="Group name" value={item.name} onChange={(value) => updateList("skillGroups", index, "name", value)} /><NumberField label="Order" value={item.order} onChange={(value) => updateList("skillGroups", index, "order", value)} /><Field className="md:col-span-2" label="Skills — one per line" multiline value={textList(item.skills)} onChange={(value) => updateList("skillGroups", index, "skills", parseList(value))} /></div><Visible item={item} onChange={(value) => updateList("skillGroups", index, "visible", value)} /></ItemCard>)}</Collection>
    <Collection title="Resume projects" addLabel="Add project" onAdd={() => addItem("projects", { title: "", dateLabel: "", techStack: [], liveUrl: "", githubUrl: "", bullets: [] })}>{content.projects.map((item, index) => <ItemCard key={item._id || index} onRemove={() => removeItem("projects", index)}><div className="grid gap-4 md:grid-cols-2"><Field label="Project title" value={item.title} onChange={(value) => updateList("projects", index, "title", value)} /><Field label="Date / type" value={item.dateLabel} onChange={(value) => updateList("projects", index, "dateLabel", value)} /><Field label="Live URL" value={item.liveUrl} onChange={(value) => updateList("projects", index, "liveUrl", value)} /><Field label="GitHub URL" value={item.githubUrl} onChange={(value) => updateList("projects", index, "githubUrl", value)} /><NumberField label="Order" value={item.order} onChange={(value) => updateList("projects", index, "order", value)} /><Field className="md:col-span-2" label="Tech stack — one per line" multiline value={textList(item.techStack)} onChange={(value) => updateList("projects", index, "techStack", parseList(value))} /><Field className="md:col-span-2" label="Project bullets — one per line" multiline value={textList(item.bullets)} onChange={(value) => updateList("projects", index, "bullets", parseList(value))} /></div><Visible item={item} onChange={(value) => updateList("projects", index, "visible", value)} /></ItemCard>)}</Collection>
    <Collection title="Education" addLabel="Add education" onAdd={() => addItem("education", { title: "", institution: "", details: "", yearLabel: "", score: "" })}>{content.education.map((item, index) => <ItemCard key={item._id || index} onRemove={() => removeItem("education", index)}><div className="grid gap-4 md:grid-cols-2"><Field label="Title" value={item.title} onChange={(value) => updateList("education", index, "title", value)} /><Field label="Year label" value={item.yearLabel} onChange={(value) => updateList("education", index, "yearLabel", value)} /><Field label="Institution" value={item.institution} onChange={(value) => updateList("education", index, "institution", value)} /><Field label="Score" value={item.score} onChange={(value) => updateList("education", index, "score", value)} /><Field className="md:col-span-2" label="Details" value={item.details} onChange={(value) => updateList("education", index, "details", value)} /><NumberField label="Order" value={item.order} onChange={(value) => updateList("education", index, "order", value)} /></div><Visible item={item} onChange={(value) => updateList("education", index, "visible", value)} /></ItemCard>)}</Collection>
    <Collection title="Training & certification" addLabel="Add training" onAdd={() => addItem("training", { title: "", details: "", certificateStatus: "" })}>{content.training.map((item, index) => <ItemCard key={item._id || index} onRemove={() => removeItem("training", index)}><div className="grid gap-4 md:grid-cols-2"><Field label="Title" value={item.title} onChange={(value) => updateList("training", index, "title", value)} /><NumberField label="Order" value={item.order} onChange={(value) => updateList("training", index, "order", value)} /><Field className="md:col-span-2" label="Details" value={item.details} onChange={(value) => updateList("training", index, "details", value)} /><Field className="md:col-span-2" label="Certificate status" value={item.certificateStatus} onChange={(value) => updateList("training", index, "certificateStatus", value)} /></div><Visible item={item} onChange={(value) => updateList("training", index, "visible", value)} /></ItemCard>)}</Collection>
    <Collection title="Achievements" addLabel="Add achievement" onAdd={() => addItem("achievements", { title: "", description: "" })}>{content.achievements.map((item, index) => <ItemCard key={item._id || index} onRemove={() => removeItem("achievements", index)}><div className="grid gap-4 md:grid-cols-2"><Field label="Title" value={item.title} onChange={(value) => updateList("achievements", index, "title", value)} /><NumberField label="Order" value={item.order} onChange={(value) => updateList("achievements", index, "order", value)} /><Field className="md:col-span-2" label="Description" multiline value={item.description} onChange={(value) => updateList("achievements", index, "description", value)} /></div><Visible item={item} onChange={(value) => updateList("achievements", index, "visible", value)} /></ItemCard>)}</Collection>
    <Collection title="Languages" addLabel="Add language" onAdd={() => addItem("languages", { name: "" })}>{content.languages.map((item, index) => <ItemCard key={item._id || index} onRemove={() => removeItem("languages", index)}><div className="grid gap-4 md:grid-cols-2"><Field label="Language" value={item.name} onChange={(value) => updateList("languages", index, "name", value)} /><NumberField label="Order" value={item.order} onChange={(value) => updateList("languages", index, "order", value)} /></div><Visible item={item} onChange={(value) => updateList("languages", index, "visible", value)} /></ItemCard>)}</Collection>
    <Feedback error={error} message={message} /><button type="submit" disabled={isSaving || isUploading} className="cursor-pointer rounded-lg bg-[#e82b45] px-5 py-3 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-60">{isSaving ? "Saving..." : "Save Resume"}</button>
  </form>;
}

function Section({ title, description, children }) { return <section className="space-y-5 rounded-2xl border border-white/10 bg-white/[0.03] p-5 sm:p-6"><div><h3 className="text-base font-semibold text-white">{title}</h3>{description && <p className="mt-1 text-sm text-white/55">{description}</p>}</div>{children}</section>; }
function Collection({ title, addLabel, onAdd, children }) { return <Section title={title}><div className="space-y-4">{children}</div><button type="button" onClick={onAdd} className="cursor-pointer rounded-lg border border-white/15 px-4 py-2 text-sm font-medium text-white/80 transition hover:border-[#e82b45] hover:text-white">+ {addLabel}</button></Section>; }
function ItemCard({ children, onRemove }) { return <div className="space-y-4 rounded-xl border border-white/10 bg-black/10 p-4"><div className="flex justify-end"><button type="button" onClick={onRemove} className="cursor-pointer text-xs font-medium text-[#ff9baa] hover:text-white">Remove</button></div>{children}</div>; }
function NumberField({ label, value, onChange }) { return <label className="block min-w-0 text-sm font-medium text-white/80">{label}<input type="number" value={value ?? 0} onChange={(event) => onChange(Number(event.target.value) || 0)} className="mt-2 w-full min-w-0 rounded-lg border border-white/15 bg-black/15 px-3 py-2.5 text-sm text-white outline-none focus:border-[#e82b45]" /></label>; }
function Visible({ item, onChange }) { return <label className="flex cursor-pointer items-center gap-3 text-sm font-medium text-white/75"><input type="checkbox" checked={item.visible !== false} onChange={(event) => onChange(event.target.checked)} /> Show publicly</label>; }
