"use client";

import { useEffect, useState } from "react";
import { apiRequest } from "@/lib/api";
import { AdminIntro, AdminStatus, Feedback } from "@/components/admin/HeroManager";

const emptyLink = { label: "", url: "", iconKey: "", order: "", visible: true };
const inputClass = "mt-2 w-full rounded-lg border border-white/15 bg-black/15 px-3 py-2.5 text-sm text-white outline-none focus:border-[#e82b45]";
const actionClass = "rounded-lg border border-white/15 px-3 py-2 text-sm text-white/80 hover:border-[#e82b45]";

export default function SocialLinksManager() {
  const [items, setItems] = useState([]); const [form, setForm] = useState(emptyLink); const [editingId, setEditingId] = useState(null); const [isLoading, setIsLoading] = useState(true); const [isSaving, setIsSaving] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const sortItems = (links) => [...links].sort((first, second) => first.order - second.order);
  useEffect(() => { const timer = window.setTimeout(async () => { try { const response = await apiRequest("/api/admin/social-links"); setItems(sortItems(response.data)); } catch (requestError) { setError(requestError.message); } finally { setIsLoading(false); } }, 0); return () => window.clearTimeout(timer); }, []);
  function beginEdit(item) { setEditingId(item?._id || null); setForm(item ? { ...emptyLink, ...item, order: String(item.order ?? "") } : emptyLink); setError(""); setMessage(""); }
  function update(field, value) { setForm((current) => ({ ...current, [field]: value })); }
  async function save(event) { event.preventDefault(); setError(""); setMessage(""); if (!/^https?:\/\//i.test(form.url)) { setError("URL must begin with http:// or https://."); return; } setIsSaving(true); try { const response = await apiRequest(editingId ? `/api/admin/social-links/${editingId}` : "/api/admin/social-links", { method: editingId ? "PATCH" : "POST", body: JSON.stringify({ ...form, order: form.order === "" ? undefined : Number(form.order) }) }); setItems((current) => sortItems(editingId ? current.map((item) => item._id === editingId ? response.data : item) : [...current, response.data])); setEditingId(null); setForm(emptyLink); setMessage("Social link saved successfully."); } catch (requestError) { setError(requestError.message); } finally { setIsSaving(false); } }
  async function remove(item) { if (!window.confirm(`Delete “${item.label}”?`)) return; setError(""); try { await apiRequest(`/api/admin/social-links/${item._id}`, { method: "DELETE" }); setItems((current) => current.filter((link) => link._id !== item._id)); setMessage("Social link deleted."); } catch (requestError) { setError(requestError.message); } }
  if (isLoading) return <AdminStatus text="Loading social links..." />;
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><AdminIntro title="Social Links Management" text="Manage the visible links in the Find Me Online area." /><button type="button" onClick={() => beginEdit()} className="rounded-lg bg-[#e82b45] px-4 py-2.5 text-sm font-semibold text-white">+ Add Social Link</button></div><Feedback error={error} message={message} /><form onSubmit={save} className="grid gap-4 rounded-2xl border border-white/10 bg-white/[0.03] p-5 sm:grid-cols-2 sm:p-6"><Field label="Label *" value={form.label} required onChange={(value) => update("label", value)} /><Field label="URL *" value={form.url} required onChange={(value) => update("url", value)} /><Field label="Icon Key" value={form.iconKey} onChange={(value) => update("iconKey", value)} /><label className="block text-sm font-medium text-white/80">Order<input type="number" value={form.order} onChange={(event) => update("order", event.target.value)} className={inputClass} /></label><label className="flex items-center gap-3 text-sm font-medium text-white/80 sm:col-span-2"><input type="checkbox" checked={form.visible} onChange={(event) => update("visible", event.target.checked)} /> Visible publicly</label><div className="flex gap-3 sm:col-span-2"><button disabled={isSaving} className="rounded-lg bg-[#e82b45] px-5 py-3 text-sm font-semibold text-white disabled:opacity-60">{isSaving ? "Saving..." : editingId ? "Save Link" : "Add Link"}</button><button type="button" onClick={() => beginEdit()} className={actionClass}>Cancel</button></div></form><section className="space-y-3">{items.map((item) => <article key={item._id} className="flex flex-wrap items-center justify-between gap-4 rounded-xl border border-white/10 bg-white/[0.03] p-4"><div className="min-w-0"><p className="font-semibold text-white">{item.label}</p><p className="mt-1 truncate text-sm text-white/55">{item.url}</p><p className="mt-2 text-xs text-white/45">{item.iconKey || "generic"} · Order {item.order} · {item.visible ? "Visible" : "Hidden"}</p></div><div className="flex gap-2"><button type="button" onClick={() => beginEdit(item)} className={actionClass}>Edit</button><button type="button" onClick={() => remove(item)} className={actionClass}>Delete</button></div></article>)}{!items.length && <AdminStatus text="No social links saved yet." />}</section></div>;
}
function Field({ label, value, onChange, required = false }) { return <label className="block text-sm font-medium text-white/80">{label}<input value={value} required={required} onChange={(event) => onChange(event.target.value)} className={inputClass} /></label>; }
